channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.11.13=h1a3bd86_0
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h993c535_1
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==1.8.1
      - addict==2.4.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - aiosqlite==0.21.0
      - airportsdata==20250706
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anthropic==0.71.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - apache-tvm-ffi==0.1.2
      - astor==0.8.1
      - asttokens==3.0.0
      - attrs==25.4.0
      - backtranslation
      - banks==2.2.0
      - beautifulsoup4==4.14.2
      - bitsandbytes==0.48.2
      - blake3==1.0.8
      - blessed==1.22.0
      - blobfile==3.0.0
      - boto3==1.39.3
      - botocore==1.39.3
      - build==1.2.2.post1
      - cachetools==6.2.2
      - cbor2==5.7.1
      - certifi==2025.11.12
      - cffi==2.0.0
      - chardet==3.0.4
      - charset-normalizer==3.4.4
      - click==8.2.1
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - colorlog==6.9.0
      - comm==0.2.3
      - compressed-tensors==0.12.2
      - contourpy==1.3.2
      - cryptography==45.0.5
      - cuda-bindings==13.0.3
      - cuda-pathfinder==1.3.2
      - cuda-python==13.0.3
      - cupy-cuda12x==13.6.0
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - datasets==3.6.0
      - decorator==5.2.1
      - decord==0.6.0
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - depyf==0.20.0
      - dill==0.3.8
      - dirtyjson==1.0.8
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.8.0
      - doclayout-yolo==0.0.4
      - docstring-parser==0.17.0
      - easydict==1.13
      - einops==0.8.1
      - email-validator==2.3.0
      - executing==2.2.0
      - fast-langdetect==0.2.5
      - fastapi==0.121.2
      - fastapi-cli==0.0.16
      - fastapi-cloud-cli==0.3.1
      - fastrlock==0.8.3
      - fasttext-predict==0.9.2.4
      - ffmpy==0.6.0
      - filelock==3.20.0
      - filetype==1.2.0
      - flash-attn==2.8.3
      - flashinfer-python==0.5.2
      - flatbuffers==25.2.10
      - fonttools==4.58.5
      - fpdf==1.7.2
      - frozendict==2.4.7
      - frozenlist==1.8.0
      - fsspec==2025.3.0
      - ftfy==6.3.1
      - future==1.0.0
      - gdown==5.2.0
      - gguf==0.17.1
      - googletrans
      - gradio==5.35.0
      - gradio-client==1.10.4
      - gradio-pdf==0.0.22
      - greenlet==3.2.4
      - griffe==1.12.1
      - groovy==0.1.2
      - grpcio==1.74.0
      - h11==0.16.0
      - h2==3.2.0
      - hf-transfer==0.1.9
      - hf-xet==1.2.0
      - hpack==3.0.0
      - hstspreload==2025.1.1
      - httpcore==1.0.9
      - httplib2==0.22.0
      - httptools==0.7.1
      - httpx
      - httpx-retries==0.4.5
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - hyperframe==5.2.0
      - idna==2.10
      - imageio==2.37.0
      - img2pdf==0.6.3
      - importlib-metadata==8.7.0
      - interegular==0.3.3
      - ipython==9.4.0
      - ipython-ngql==0.14.3
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.7
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.12.0
      - jmespath==1.0.1
      - joblib==1.5.1
      - json-repair==0.47.6
      - jsonpickle==4.1.1
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.8
      - lark==1.2.2
      - lazy-loader==0.4
      - litellm==1.74.0.post1
      - llama-cloud==0.1.35
      - llama-cloud-services==0.6.54
      - llama-index==0.13.2
      - llama-index-cli==0.5.0
      - llama-index-core==0.13.2
      - llama-index-embeddings-openai==0.5.0
      - llama-index-graph-stores-nebula==0.5.0
      - llama-index-indices-managed-llama-cloud==0.9.2
      - llama-index-instrumentation==0.4.0
      - llama-index-llms-openai==0.5.4
      - llama-index-readers-file==0.5.2
      - llama-index-readers-llama-parse==0.5.0
      - llama-index-readers-milvus==0.4.0
      - llama-index-vector-stores-milvus==0.9.0
      - llama-index-workflows==1.3.0
      - llama-parse==0.6.54
      - llguidance==1.3.0
      - llvmlite==0.44.0
      - lm-format-enforcer==0.11.3
      - loguru==0.7.3
      - lxml==6.0.0
      - magika==0.6.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - marshmallow==3.26.1
      - matplotlib==3.10.3
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - milvus-lite==2.5.1
      - mineru==2.6.4
      - mineru-vl-utils==0.1.15
      - mistral-common==1.8.5
      - model-hosting-container-standards==0.1.6
      - modelscope==1.27.1
      - mpmath==1.3.0
      - msgpack==1.1.2
      - msgspec==0.19.0
      - multidict==6.7.0
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - nebula3-python==3.8.3
      - nest-asyncio==1.6.0
      - networkx==3.6rc0
      - ninja==1.13.0
      - nlpaug==1.1.11
      - nltk==3.9.1
      - numba==0.61.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cudnn-frontend==1.16.0
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-cutlass-dsl==4.3.0.dev0
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - ollama==0.6.1
      - omegaconf==2.3.0
      - onnxruntime==1.22.0
      - openai==2.14.0
      - openai-harmony==0.0.8
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - opentelemetry-api==1.38.0
      - opentelemetry-sdk==1.38.0
      - opentelemetry-semantic-conventions==0.59b0
      - orjson==3.10.18
      - outlines==0.1.11
      - outlines-core==0.2.11
      - packaging==25.0
      - pandas==2.2.3
      - parso==0.8.4
      - partial-json-parser==0.2.1.1.post6
      - pdfminer-six==20250506
      - pdftext==0.6.3
      - pexpect==4.9.0
      - pikepdf==10.0.2
      - pillow==12.0.0
      - platformdirs==4.3.8
      - prometheus-client==0.23.1
      - prometheus-fastapi-instrumentator==7.1.0
      - prompt-toolkit==3.0.51
      - propcache==0.4.1
      - protobuf==6.33.1
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==20.0.0
      - pybase64==1.4.2
      - pyclipper==1.3.0.post6
      - pycountry==24.6.1
      - pycparser==2.23
      - pycryptodomex==3.23.0
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydantic-extra-types==2.10.6
      - pydantic-settings==2.10.1
      - pydub==0.25.1
      - pygments==2.19.2
      - pymilvus==2.6.0
      - pymupdf==1.26.5
      - pynvml==12.0.0
      - pyparsing==3.2.3
      - pypdf==5.7.0
      - pypdf2==3.0.1
      - pypdfium2==4.30.0
      - pyproject-hooks==1.2.0
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyvis==0.3.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - rapid-table==1.0.5
      - ray==2.51.1
      - referencing==0.37.0
      - regex==2025.11.3
      - reportlab==4.4.2
      - requests==2.32.5
      - rfc3986==1.5.0
      - rich==14.2.0
      - rich-toolkit==0.15.1
      - rignore==0.7.6
      - robust-downloader==0.0.2
      - rpds-py==0.28.0
      - ruff==0.12.2
      - s3transfer==0.13.0
      - safehttpx==0.1.6
      - safetensors==0.7.0rc0
      - scikit-image==0.25.2
      - scikit-learn==1.7.1
      - scipy==1.16.3
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentence-transformers==5.1.0
      - sentencepiece==0.2.1
      - sentry-sdk==3.0.0a7
      - setproctitle==1.3.7
      - setuptools==80.9.0
      - sgl-kernel==0.2.6.post1
      - sglang==0.4.9.post3
      - shapely==2.1.1
      - shellingham==1.5.4
      - simsimd==6.5.0
      - six==1.17.0
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soupsieve==2.7
      - soxr==1.0.0
      - sqlalchemy==2.0.43
      - stack-data==0.6.3
      - starlette==0.49.3
      - stringzilla==3.12.5
      - striprtf==0.0.26
      - supervisor==4.3.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - tenacity==9.1.2
      - thop==0.1.1-2209072238
      - threadpoolctl==3.6.0
      - tifffile==2025.9.30
      - tiktoken==0.12.0
      - timm==1.0.16
      - tokenizers==0.22.1
      - tomlkit==0.13.3
      - torch==2.9.0
      - torch-memory-saver==0.0.8
      - torchao==0.9.0
      - torchaudio==2.9.0
      - torchvision==0.24.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.1
      - triton==3.5.0
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - ujson==5.10.0
      - ultralytics==8.3.163
      - ultralytics-thop==2.0.14
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - watchfiles==1.1.1
      - wcwidth==0.2.13
      - websockets==15.0.1
      - widgetsnbextension==4.0.14
      - wrapt==1.17.3
      - xformers==0.0.33
      - xgrammar==0.1.25
      - xxhash==3.5.0
      - yarl==1.22.0
      - zipp==3.23.0
